### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by aelsenaar** [cdriget/DomoCharts#1]
I really like you solution to gather statistics for the Fibaro box.

I have a question; after installing the web application some resources from style.css are missing.

E.g:
img/bg.png
img/bg_content_first_section.png
img/bg_content_room.png

Can you please provide these files?

**Comment by cdriget** [comment]
Hi,

Yes, Images, CSS, and Jquery extensions are missing.
You can find the full package on the french non-official Fibaro forum : http://www.domotique-fibaro.fr/index.php/topic/466-graph-de-temp%C3%A9rature-humidit%C3%A9-consommationsur-nas/
You need to create an account and introduce youself to be able to download files.

**Comment by aelsenaar** [comment]
Hi,

Thanks for the reply. I already created an account. But still get an error about missing permissions How can I solve that? Introduce myself? How?

**Comment by cdriget** [comment]
Create a new thread in this section : http://www.domotique-fibaro.fr/index.php/forum/6-nouveau-pr%C3%A9sentez-vous/
Just click on the "Commencer un sujet" button. Then you can write in english, that's OK.

**Comment by aelsenaar** [comment]
Great, thanks!

My French is a little bit rusty.

Alexander

2016-01-25 21:48 GMT+01:00 Christophe DRIGET notifications@github.com:

> Create a new thread in this section :
> http://www.domotique-fibaro.fr/index.php/forum/6-nouveau-pr%C3%A9sentez-vous/
> Just click on the "Commencer un sujet" button. Then you can write in
> english, that's OK.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cdriget/DomoCharts/issues/1#issuecomment-174657970.

## 

Alexander Elsenaar
